name: Build and deploy ASP.Net Core app to Azure Web App - eduwork

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      PROJECT_PATH: ./EduWork.WebApi

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build EduWork.UI
        run: | 
          cd EduWork.UI
          dotnet build --configuration Release

      - name: Publish EduWork.UI
        run: | 
          cd EduWork.UI
          dotnet publish ${{env.CLIENT_PATH}} -c Release -o ../EduWork.WebApi

      - name: Build EduWork.WebApi
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --verbosity normal

      - name: Publish EduWork.WebApi
        run: dotnet publish ${{env.PROJECT_PATH}} -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_213EB91F9D1F4398B21344BD9C4C8C0F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_02859C7DE34146BAB294CE3DB1D06388 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3EA44497524449B893EB49BBE3263BD9 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eduwork'
          slot-name: 'Production'
          package: .
          